### ISSUE TITLE
Need Requirements Details

### ISSUE THREAD

**Issue by SheffieldCao** [wencheng256/BRNet#2]
Could you please provide more environment details, because I saw that you used `nn.MultiheadAttention` in `resnet_encoder.py`. But there is no `nn.MultiheadAttention` in torch.nn in pytorch older than v1.1. It seems that you just copy the  ⚙️ **Setup** part of [monodepth2](https://github.com/nianticlabs/monodepth2). 😂

**Comment by wencheng256** [comment]
Thank you for your attention. I apologize that I did not organize my code well. For your first question 1x1conv. It is actually not used at all because the residual block used here always has a stride=1. I just forgot to delete the unused code.
For your second question the` nn.MultiheadAttention`,  please use pytorch with a higher version. I will update the related requirements.

**Comment by SheffieldCao** [comment]
Thank you!
